---
title: A landing Page Template by jprefer.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://landing.jprefer.com
email: john@jprefer.com
author: John Prefer
description: 'This is my new test site with a downloaded theme from Jeckyll

'
copyright: Copyright &copy; 2018 John Prefer. All Rights Reserved.
credits: 'Credits: Thank you startbootstrap.com.'
markdown: kramdown
permalink: pretty
social:
- title: twitter
  url: https://twitter.com/jprefer
- title: github
  url: https://github.com/jprefer
- title: linkedin
  url: 
  
  plugins:
  - jekyll-sitemap
  
  
